### ISSUE TITLE
Drag Hero Fragment outside any container, dissappears

### ISSUE THREAD

**Issue by Cavitedev** [JoseLu-Dev/SimpleAndroidRPG#2]
It needs a check to not move the hero in that case
![image](https://user-images.githubusercontent.com/52750778/98517173-cc578700-226d-11eb-837c-5c22d36717b0.png)

**Comment by JoseLu-Dev** [comment]
It does not really move the hero, it just becomes invisible, try to do changes on the formation and reload the activity, changes on formation are saved while you have the app opened

**Comment by Cavitedev** [comment]
JoseLu-Dev has dixed it on last commit
